# build stage
FROM golang:1.22 AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o app main.go

# run stage
FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/app .

EXPOSE 8080
CMD ["./app"]
