development:
  dialect: postgres
  datasource: host=postgres.railway.internal port=5432 user=postgres password=UJscaMybCULqDLisvrgODIFVnmhgZARg dbname=railway sslmode=disable
  dir: database/migrations
  table: migrations
