development:
  dialect: postgres
  datasource: host=containers-us-west-209.railway.app port=6787 user=postgres password=klvdwsmPTiyabcaeh63 dbname=railway sslmode=disable
  dir: database/migrations
  table: migrations
